openapi: 3.0.3
info:
  title: Eux PDF flattener
  description: API til bruk av Eux-apper for å gjøre utfyllbare PDF-er om til statiske PDF-er.
  contact:
    name: knut.bjornar.walberg@nav.no
  version: v1
servers:
  - url: 'http://localhost:8080/api/v1'
tags:
  - name: Eux PDF flattener
    description: >-
      API til bruk av Eux-apper for å gjøre utfyllbare PDF-er om til statiske PDF-er.

paths:
  /pdf:
    $ref: 'pdf/operations_pdf.yaml'

