kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ name }}
  namespace: eessibasis
  labels:
    team: eessibasis
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  image: {{ image }}
  ingresses:
    - {{ ingress }}
  liveness:
    path: /actuator/health
    port: 8080
    initialDelay: 50
    timeout: 150
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health
    port: 8080
    initialDelay: 50
    timeout: 150
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "1"
      memory: 3072Mi
    requests:
      cpu: 250m
      memory: 2048Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      replyURLs:
        - "{{ ingress }}/callback"
      claims:
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /api/**
  accessPolicy:
    inbound:
      rules:
        - application: {{ application.eux-fagmodul-journalfoering.name }}
          namespace: {{ application.eux-fagmodul-journalfoering.namespace }}
          cluster: {{ cluster.fss }}
